name = "smpark-dev" # Change name
type = "webpack"
account_id = "{{ ACCOUNT_ID }}" # Replace with your Cloudflare account id
workers_dev = true # Change when using custom domain
route = ""
zone_id = ""

[site]
bucket = "./_site"
entry-point = "workers-site"
